# Site settings
title: 贺治东的博客
SEOTitle: 贺治东的博客
header-img: assets/img/home-bg.jpg
email: w-s-h-z-d@163.com
description: "NLP Researcher"
keyword: ""
url: "http://wshzd.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'
excerpt_separator: "<!--more-->"

# Name of your site (displayed in the header)
name: "Arron's HomePage"
# Short bio or description (displayed in the header)
description: "NLP Researcher"


# SNS settings
RSS: true
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    wshzd
#twitter_username:  huxpro
#facebook_username:  huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
# Exclude these files from your production _site
exclude: ["Gemfile","Gemfile.lock","LICENSE","CNAME","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Gems
# from PR#40, to support local preview for Jekyll 3.0, Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: wshzd

# Duoshuo settings
duoshuo_username:  
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
# ba_track_id: 1adf2d3145a435baa683d84388135812
# Google Analytics
# ga_track_id: 'UA-133955198-1'            # Format: UA-xxxxxx-xx
# ga_domain: fancyerii.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "读读论文，写写代码。"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

collections:
  books:
    output: true





# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: assets/img/ArronAI.jpg
# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://raw.githubusercontent.com/wshzd/wshzd.github.io/master/assets/img/favicon.ico

# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: HOME
    url: /
  - name: ABOUT
    url: /about
  - name: ARCHIVE
    url: /archive
  - name: TAGS
    url: /tags

# excerpt_separator: <!-- more -->

# Includes an icon in the footer for each username you enter
footer-links:
  #weibo: frommidworld #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<username>
  dribbble:
  zhihu: he-zhi-dong-87
  email: w-s-h-z-d@163.com
  facebook:
  flickr:
  github: wshzd 
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  #twitter: frommidworld
  youtube:

# Text under the icons in footer
footer-text: Copyright (c) 2023 Arron

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: # fromendworld

# Gitalk
gitalk:
  clientID: 11ad1f735e14463cff22
  clientSecret: 39f27fdf1db389b7019d776b496030ee54b90076
  repo: wshzd.github.io
  owner: wshzd

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
#google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://wshzd.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# baseurl: 

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

